### ISSUE TITLE
<effect> tag mangled badly with Tags API

### ISSUE THREAD

**Issue by vwong** [marko-js/prettier#7]
### Details

It is mangling up `<effect>` beyond use, introducing syntax errors everywhere.

### Your Environment

Node 16.13.2, Mac OS 12.3

### Steps to Reproduce

Before:
```
<effect() {
  const listener = () => { isVisible = true; }
  window.addEventListener(`eventbus:${listenTo}`, listener);

  return () => {
    window.removeEventListener(`eventbus:${listenTo}`, listener);
  }
}/>
```

After:
```
<effect() {
ffect() {
  const listener = () => { isVisib
  const listener = () => {
    isVisible = true;
  };
  window.addE;
 return () => {

}/>
```

**Comment by Nick-Mazuk** [comment]
I noticed this, too. Also with the `<attrs>` tag. Dug through the code and I think this isn't fixible until the new compiler comes out—or there's a way also make sure prettier recognizes the `@markojs/tags-api-preview` dependency.

For those curious, here's what I learned before it got late enough that I needed to go to bed.

`effect()` tags are considered `"ExpressionStatement"`s and not a Marko specific statement. So when this switch happens, `node.type === "ExpressionStatement"`. 

https://github.com/marko-js/prettier/blob/28c3d32d1aabd7a6f948fc09457fe01e1c7b335f/src/index.ts#L180-L187

This switch doesn't check for that type of node, so we reach the base case and things go wild:

https://github.com/marko-js/prettier/blob/28c3d32d1aabd7a6f948fc09457fe01e1c7b335f/src/index.ts#L579-L580

That means the actual bug is likely in how the AST is parsed. And the AST is created here in the `compileSync` function provided by `@marko-js/compiler`.

https://github.com/marko-js/prettier/blob/28c3d32d1aabd7a6f948fc09457fe01e1c7b335f/src/index.ts#L112

That means the root cause probably has something to do with the marko compiler not registering the `@marko-js/tags-api-preview` package.

That's about as far as I got. Would be really curious to see if the maintainers could get further.
